### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/gpt.do-archive#1]
```[tasklist]
### Roadmap
- [x] #2
- [ ] #3
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] Conversation tail summary for model token limits
- [ ] Named conversation route
- [ ] https://github.com/drivly/gpt.do/issues/9
- [ ] Drop in kafka.do replacement
```

**Comment by sam-lippert** [comment]
@nathanclevenger Could you please add clarifying comments to these roadmap items and https://github.com/drivly/repo.do/issues/1?

**Comment by nathanclevenger** [comment]
Sure @sam-lippert! #4 #5 and #6 are all about enabling GPT to take actions on a GitHub repo.  So for example, #4 is a pre-requisite for #5 which is required for #6 where an issue could be created, and assigned to the @chat-gpt-do or @repo-do users, where a response could be generated, and a discussion back and forth  - where eventually it could even write or edit a file with a pull request.  Very similar to what GPT Engineer is going as a CLI, but rather as a GitHub App and as-a-Service

I think that https://github.com/drivly/repo.do/issues/1 could potentially be the basis for the above items, but repo.do can have many other benefits beyond GPT interactions, as a convenience API for Issues, Gists, PRs, etc
